In [7]:
from numpy.linalg import solve
from numpy import array
import numpy as np

In [10]:
A = array([[3,2,2], [1,6,-1], [4,1,5]])
b_1 = array([-1,3,-6])

In [17]:
x = np.round(solve(A,b_1), 5)
y

array([-0.,  0.,  0.])

In [18]:
np.dot(A,x) # A * x

array([-1.,  3., -6.])

In [30]:
B = array([[1,3,2], [2,-2, 5], [-3, 3, -2]])
b_2 = np.array([0,0,0]) # same as np.zeros(3)

In [31]:
y = solve(B,b_2)
y

array([-0.,  0.,  0.])

In [32]:
np.dot(B, y) # B * y

array([0., 0., 0.])

In [33]:
M = array([[1,-1], [0, 2]])
M

array([[ 1, -1],
       [ 0,  2]])

In [39]:
np.linalg.eig(M)

(array([1., 2.]),
 array([[ 1.        , -0.70710678],
        [ 0.        ,  0.70710678]]))