In [2]:
import numpy as np

In [41]:
# Create matrix A and vector B_1

A = np.array([[3,2,2], [1,6,-1], [4,1,5]])
b = np.array([-1,3,-6])

In [42]:
# Solve linear system of the form Ax = b
# round result to 5 digits, output result

x = np.round(np.linalg.solve(A,b), 5)
x

array([ 1., -0., -2.])

In [43]:
# optional, check if A * x really outputs vector b

np.dot(A,x)

array([-1.,  3., -6.])

In [44]:
# Create matrix B and vector

B = np.array([[1,3,2], [2,-2, 5], [-3, 3, -2]])
c = np.array([0,0,0]) # same as np.zeros(3)

In [45]:
# Solve linear system of the form By = c
# round result to 5 digits, output result

y = np.linalg.solve(B,c)
y

array([-0.,  0.,  0.])

In [46]:
np.dot(B, y) # B * y

array([0., 0., 0.])

In [47]:
# how to compute eigenvalues of with numpy

M = np.array([[1,-1], [0, 2]])
np.linalg.eig(M)

(array([1., 2.]),
 array([[ 1.        , -0.70710678],
        [ 0.        ,  0.70710678]]))

In [48]:
# output the characteristic polynomial using numpy

polynom = np.poly(M)
print(" + ".join([f"{polynom[i]} * \u03BB^{len(M)-i}" for i in range(len(M)+1)]))

1.0 * λ^2 + -3.0 * λ^1 + 2.0 * λ^0
